### ISSUE TITLE
Exception occured building docs

### ISSUE THREAD

**Issue by Hammit** [alibaba/ansible-provider-docs#26]
I have installed all the dependencies according to the documentation and run `make webdocs` in the appropriate directory however I get this error...

```
Exception occurred:
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 97, in _join_one
    exc, result = pipe.recv()
EOFError
The full traceback has been saved in /tmp/sphinx-err-1Rwvgc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The contents of `/tmp/sphinx-err-1Rwvgc.log` are as follows...

```
# Sphinx version: 1.4.8
# Python version: 2.7.16 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 78%] modules/vyos_system_module .. modules/win_pagefile_module
#   reading sources... [ 81%] modules/win_path_module .. modules/zfs_facts_module
#   reading sources... [ 84%] modules/zfs_module .. plugins/callback/osx_say
#   reading sources... [ 87%] plugins/callback/profile_roles .. plugins/inventory/yaml
#   reading sources... [ 90%] plugins/lookup .. plugins/lookup/vars
#   reading sources... [ 93%] plugins/plugins .. user_guide/command_line_tools
#   reading sources... [ 96%] user_guide/index .. user_guide/windows_winrm
#   reading sources... [100%] vmware/faq .. vmware/vmware_troubleshooting
#   
#   waiting for workers...
# Loaded extensions:
#   alabaster (0.7.12) from /home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.autodoc (1.4.8) from /home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.4.8) from /home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
Traceback (most recent call last):
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/environment.py", line 567, in update
    self._read_parallel(docnames, app, nproc=app.parallel)
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/environment.py", line 625, in _read_parallel
    tasks.join()
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 92, in join
    self._join_one()
  File "/home/byron/tmp/ansible-provider-docs/venv/local/lib/python2.7/site-packages/sphinx/util/parallel.py", line 97, in _join_one
    exc, result = pipe.recv()
EOFError
```

**Comment by Hammit** [comment]
In addition to doing this I had a previous error that was fixed by installing `pyyaml`. Is this an undocumented dependency?

**Comment by Hammit** [comment]
Ok, I just tried again and got it working but with `python3` and `pyyaml` and without the specific `sphinx` version requirement. I just installed latest sphinx version
